print ("კომპიუტერის ფასის დასადგენად მიუთითეთ ნაწილის ფასი")
print ("კლავიატურის ფასი:")
keyboard =  float(input ())
print ("მაუსის ფასი:")
mouse = float(input ())
print ("სისტემური ბლოკის ფასი:")
block = float(input ())
print ("მონიტორის ფასი:")
monitor = float(input ())
sum = keyboard + mouse + block + monitor
print ("ჯამური ფასი:", sum)
